version: '3'
services:
  authentication:
    image: lqha.xyz/authentication
    build: ../authentication
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql
      - lua_init_database
    volumes:
      - ./rbac_policy.csv:/app/rbac_policy.csv
    restart: on-failure

  lua_init_database:
    image: lqha.xyz/base-luasql-mysql:latest
    build: ./base-luasql-mysql
    environment:
      LUA_PATH: /lua/?.lua;;
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_LIB: auth
    depends_on:
      - mysql
    volumes:
      - ./lua/:/lua
    entrypoint: lua /lua/init_database.lua
    restart: on-failure

  etcd-backend:
    image: lqha.xyz/etcd_backend
    build: ../etcd_backend
    environment:
      ETCD_ADDR: etcd:2379
    depends_on:
      - etcd

  front-page:
    image: lqha.xyz/front-page
    build: ../front-page
    volumes:
      - front-page-dist:/node/front-page/dist/
    depends_on:
      - authentication
      - etcd-backend

  openresty:
    image: openresty/openresty:1.19.3.1-3-alpine
    ports:
      - "80:80"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_LIB: auth
    volumes:
      - front-page-dist:/usr/local/openresty/nginx/html/product/front-page/
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./lua/:/usr/local/openresty/lualib/custom/
    depends_on:
      - front-page
    restart: on-failure

  mysql:
    image: mysql:5.7.32
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: auth
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql

  etcd:
    image: docker.io/bitnami/etcd:3.4.13
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - ./etcd-data:/bitnami/etcd

volumes:
  front-page-dist:

